name: class2
version: 0.1.0.0

dependencies: 
  - base

library:
  exposed-modules: Class2
  source-dirs: src
  ghc-options: -Wall

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - class2
      - hspec